---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "skooner.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterRoleBinding.clusterRole }}
subjects:
- kind: ServiceAccount
  name: {{ include "skooner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
