---
apiVersion: v2
name: prometheus-pve-exporter
description: A Helm chart for bootstrapping a PVE Exporter. Uses ServiceMonitor to collect metrics.
type: application
version: 2.5.0
appVersion: "3.8.0"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/prometheus-pve-exporter/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/prometheus-pve/prometheus-pve-exporter
annotations:
  artifacthub.io/alternativeName: "pve-exporter"
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - kind: added
      description: Add Ingress resource and `ingress` values to expose the exporter via Ingress.
    - kind: fixed
      description: helm schema
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/screenshots: |
    - title: Add an user inside of Proxmox, that will be used for the Exporter.
      url: https://xinux.net/images/6/6e/Prometheus-proxmox-grafana-user.png
    - title: Add permissions for this user.
      url: https://xinux.net/images/5/5d/Prometheus-proxmox-grafana-user-permission.png
    - title: Visualize the data collected with Grafana.
      url: https://grafana.com/api/dashboards/10347/images/6529/image
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
