apiVersion: v2
name: proxyweb
description: A Helm chart for Kubernetes
type: application
version: 1.0.6
appVersion: "latest"
home: https://github.com/christianhuth/helm-charts
maintainers: []
sources:
  - https://github.com/edmodo/proxyweb/
deprecated: true
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Changelog
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
