apiVersion: v2
name: mcp-for-argocd
description: An implementation of Model Context Protocol (MCP) server for Argo CD
type: application
version: 1.0.0
appVersion: "v0.5.0"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/mcp-for-argocd/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/argoproj-labs/mcp-for-argocd
annotations:
  artifacthub.io/category: ai-machine-learning
  artifacthub.io/changes: |
    - kind: added
      description: initial version
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
