apiVersion: v2
name: ntp-exporter
description: Prometheus exporter that checks the drift of Kubernetes node's clock against a given NTP server or servers
type: application
version: 1.2.1
appVersion: "v2.9.0"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/ntp-exporter/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/sapcc/ntp_exporter
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - kind: fixed
      description: README
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
