---
apiVersion: v2
name: syncstorage-rs
description: A Helm chart for deploying Mozilla's Firefox Sync Storage server to Kubernetes
type: application
version: 4.1.1
appVersion: "syncstorage-rs-mysql-0.18.2"
home: https://github.com/christianknell/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/syncstorage-rs/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/mozilla-services/syncstorage-rs
  - https://github.com/porelli/firefox-sync
  - https://github.com/porelli/firefox-sync/pkgs/container/firefox-sync
dependencies:
  - name: mariadb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 24.0.3
    alias: syncserver-db
    condition: syncserver-db.enabled
  - name: mariadb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 24.0.3
    alias: tokenserver-db
    condition: tokenserver-db.enabled
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: dependency of mariadb mariadb to 24.0.3
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
