{{- if (not .Values.maildev.config.smtp.outgoing.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maildev.smtp.outgoing.secretName" . }}
data:
  smtp-outgoing-password: {{ .Values.maildev.config.smtp.outgoing.password | b64enc | quote }}
{{- end }}
