apiVersion: v2
name: popeye
description: Popeye - A Kubernetes Cluster Sanitizer
type: application
version: 2.1.3
appVersion: "v0.21.3"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_logo.png
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/derailed/popeye
annotations:
  artifacthub.io/category: security
  artifacthub.io/changes: |
    - kind: changed
      description: README format
  artifacthub.io/screenshots: |
    - title: Popeye is a utility that scans live Kubernetes cluster and reports potential issues with deployed resources and configurations.
      url: https://popeyecli.io/assets/d_score.png
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
