apiVersion: v2
name: etcd-defrag
description: A Helm chart for running a defragmentation CronJob for ETCD
type: application
version: 1.2.4
appVersion: "3.5.19"
home: https://github.com/christianhuth/helm-charts
icon: https://cdn.worldvectorlogo.com/logos/etcd-1.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/etcd
  - https://etcd.io
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: App version to 3.5.19
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
