apiVersion: v2
name: etcd-defrag
description: A Helm chart for running a defragmentation CronJob for ETCD
type: application
version: 1.5.5
appVersion: "v3.6.7"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/etcd-defrag/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://quay.io/repository/coreos/etcd
  - https://etcd.io
annotations:
  artifacthub.io/changes: |
    - kind: fixes
      description: helm schema
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
