apiVersion: v2
name: proxysql
description: A proxysql Helm chart for Kubernetes. Offers option to expose web interface through Ingress. Uses ServiceMonitor to collect metrics.
type: application
version: 1.3.5
appVersion: "2.7.3"
home: https://github.com/christianhuth/helm-charts
icon: https://proxysql.com/wp-content/uploads/2019/11/ProxySQL-BIG-e1581368792603.png
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/sysown/proxysql
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: support link
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
