apiVersion: v2
name: netcupscp-exporter
description: Prometheus Exporter for Netcup Server Control Panel (SCP)
type: application
version: 1.1.5
appVersion: "v0.3.6"
home: https://github.com/christianhuth/helm-charts
icon: https://pbs.twimg.com/profile_images/1148537659637358593/rlfCvTK5_400x400.png
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/mrueg/netcupscp-exporter
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - kind: changed
      description: updated readme
  artifacthub.io/screenshots: |
    - title: Export information about your Servers from Netcup SCP as Prometheus metrics.
      url: https://www.netcup-wiki.de/images/SCP-Willkommen.png
    - title: Visualize your data as Grafana dashboard.
      url: https://raw.githubusercontent.com/mrueg/netcupscp-exporter/main/grafana/dashboard.jpg
