apiVersion: v2
description: A Helm chart to deploy workload to gain direct access to the host of the Kubernetes cluster
name: node-access
type: application
version: 1.1.2
appVersion: 1.37.0
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/kubernetes/community/master/icons/png/infrastructure_components/labeled/node-256.png
maintainers:
  - name: christianhuth
    email: christian@knell.it
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: support link
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
