{{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.auth.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "taiga.database.labels" . | nindent 4 }}
  name: {{ include "taiga.database.auth.secretName" . }}
data:
  postgres-password: {{ .Values.externalDatabase.auth.password | b64enc }}
{{- end }}
