# Explanation: Add the label 'ci-cd' to a PR if any file within the '.github' folder is changed
ci-cd: .github/*

# charts
baserow: charts/baserow/*
bluespice: charts/bluespice/*
countly: charts/countly/*
cusdis: charts/cusdis/*
dasherr: charts/dasherr/*
docker_stats_exporter: charts/docker_stats_exporter/*
ecs-exporter: charts/ecs-exporter/*
etcd-defrag: charts/etcd-defrag/*
fathom: charts/fathom/*
glances: charts/glances/*
goaccess: charts/goaccess/*
greenbone-ce: charts/greenbone-ce/*
headwind-mdm: charts/headwind-mdm/*
ipmi-exporter: charts/ipmi-exporter/*
ipsec-exporter: charts/ipsec-exporter/*
isso: charts/isso/*
kateyes: charts/kateyes/*
kirby: charts/kirby/*
kubedoom: charts/kubedoom/*
kube-ops-view: charts/kube-ops-view/*
kutt: charts/kutt/*
lxd-dashboard: charts/lxd-dashboard/*
maildev: charts/maildev/*
node-access: charts/node-access/*
netcupscp-exporter: charts/netcupscp-exporter/*
passbolt-ha: charts/passbolt-ha/*
polr: charts/polr/*
popeye: charts/popeye/*
priority-classes: charts/priority-classes/*
promlens: charts/promlens/*
prometheus-pve-exporter: charts/prometheus-pve-exporter/*
proxysql: charts/proxysql/*
proxyweb: charts/proxyweb/*
shlink-backend: charts/shlink-backend/*
shlink-web: charts/shlink-web/*
skooner: charts/skooner/*
sloop: charts/sloop/*
standardnotes: charts/standardnotes/*
syncserver: charts/syncserver/*
syncstorage-rs: charts/syncstorage-rs/*
talkyard: charts/talkyard/*
typo3: charts/typo3/*
umami: charts/umami/*
