ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  className: nginx
  hosts:
    - host: timetagger.christianhuth.de
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: timetagger.christianhuth.de-tls
      hosts:
        - timetagger.christianhuth.de

persistence:
  enabled: true
  resources:
    requests:
      storage: 1Gi
