apiVersion: v2
name: polr
description: Polr is a quick, modern, and open-source link shortener
type: application
version: 1.0.10
appVersion: "2.3.0"
home: https://github.com/christianknell/helm-charts
icon: http://docs.polrproject.org/en/latest/logo.png
maintainers:
  - name: christianknell
    email: christian@knell.it
sources:
  - https://github.com/cydrobolt/polr
  - https://github.com/ajanvier/docker-polr
dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 9.4.8
