---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcp-for-argocd.fullname" . }}
  labels:
    {{- include "mcp-for-argocd.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "mcp-for-argocd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mcp-for-argocd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mcp-for-argocd.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ARGOCD_BASE_URL
              value: {{ .Values.argocd.baseUrl | quote }}
            - name: ARGOCD_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ (include "mcp-for-argocd.auth.secretName" .) | quote }}
                  key: {{ (include "mcp-for-argocd.auth.apiToken.secretKey" .) | quote }}
            {{- if .Values.argocd.readOnly }}
            - name: MCP_READ_ONLY
              value: "true"
            {{- end }}
            {{- if .Values.argocd.skipTlsVerify }}
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            {{- end }}
            {{- if .Values.extraEnv }}
              {{- .Values.extraEnv | toYaml | nindent 12 }}
            {{- end }}
          {{- if .Values.extraEnvFrom }}
          envFrom:
            {{- .Values.extraEnvFrom | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            failureThreshold: {{ .Values.livenessProbe.failureThreshold | int }}
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | int }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | int }}
            successThreshold: {{ .Values.livenessProbe.successThreshold | int }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | int }}
          readinessProbe:
            failureThreshold: {{ .Values.readinessProbe.failureThreshold | int }}
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | int }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | int }}
            successThreshold: {{ .Values.readinessProbe.successThreshold | int }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | int }}
          startupProbe:
            failureThreshold: {{ .Values.startupProbe.failureThreshold | int }}
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds | int }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds | int }}
            successThreshold: {{ .Values.startupProbe.successThreshold | int }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds | int }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
