{{- if not .Values.argocd.auth.existingSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-for-argocd.auth.secretName" . }}
data:
  {{- (include "mcp-for-argocd.auth.apiToken.secretKey" .) | nindent 2 }}: {{ .Values.argocd.auth.apiToken | required "You need to define the API token for authentication with Argo CD" | b64enc }}
{{- end }}
