apiVersion: v2
name: goldpinger
description: Debugging tool for Kubernetes which tests and displays connectivity between nodes in the cluster.
type: application
version: 1.1.1
appVersion: "3.10.3"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/goldpinger/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/bloomberg/goldpinger
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: App Version to 3.10.3
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
