apiVersion: v2
name: cluster-api-visualizer
description: Multicluster resource visualization tool for Cluster API.
type: application
version: 0.2.0
appVersion: "v1.5.0"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/cluster-api-visualizer/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/Jont828/cluster-api-visualizer
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: App Version to v1.5.0
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/screenshots: |
    - title: Simply shorten your link using the Web UI.
      url: https://github.com/Jont828/cluster-api-visualizer/raw/main/demo/demo.gif
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
