apiVersion: v2
name: dns-exporter
description: A multi-target Prometheus exporter with an exclusive focus on DNS monitoring
type: application
version: 2.2.0
appVersion: "v1.1.0"
home: https://github.com/christianhuth/helm-charts
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/tykling/dns_exporter
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - kind: fixed
      description: problem in hpa template
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/screenshots: |
    - title: Display DNS exporter results using Grafana
      url: https://grafana.com/api/dashboards/20617/images/15803/image
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
