apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "baserow.fullname" . }}
data:
  # Baserow General Settings
  BASEROW_MAX_IMPORT_FILE_SIZE_MB: {{ .Values.config.maxImportFileSizeMb | quote }}
  BASEROW_MAX_SNAPSHOTS_PER_GROUP: {{ .Values.frontend.config.maxSnapshotsPerGroup | quote }}
  PUBLIC_BACKEND_URL: {{ include "baserow.backend.publicUrl" . | quote }}
  PUBLIC_WEB_FRONTEND_URL: {{ include "baserow.frontend.publicUrl" . | quote }}
