{{- if .Values.httproute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "freshrss.fullname" . }}
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
  {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.httproute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httproute.hostnames | nindent 4 }}
  rules:
    {{- range .Values.httproute.rules }}
    - matches:
        {{- toYaml .matches | nindent 8 }}
      backendRefs:
        {{- if .backendRefs }}
        {{- toYaml .backendRefs | nindent 8 }}
        {{- else }}
        - name: {{ include "freshrss.fullname" $ }}
          port: {{ $.Values.service.port }}
        {{- end }}
    {{- end }}
{{- end }}

