apiVersion: v2
name: headwind-mdm
description: Headwind MDM - an open source mobile device management software for Android
type: application
version: 3.1.1
appVersion: "0.1.5"
home: https://github.com/christianhuth/helm-charts
icon: https://h-mdm.com/wp-content/uploads/2019/07/neew-logo.png
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/h-mdm/hmdm-docker
  - https://github.com/h-mdm
  - https://hub.docker.com/r/headwindmdm/hmdm
dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.5.2
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: dependency to postgresql to 16.5.2
  artifacthub.io/screenshots: |
    - title: Headwind MDM is a powerful Open Source platform to manage your Enterprise Android Devices.
      url: https://images.wondershare.com/drfone/article/2022/11/opensource-mdm-3.jpg
    - title: Open the Devices section and click the QR code icon to start the enrollment of a device.
      url: https://h-mdm.com/wp-content/uploads/check_qr_code.jpg
    - title: After enrollment your Android device will only have the allowed applications installed.
      url: https://h-mdm.com/wp-content/uploads/2019/08/launcher_screen_en.png
    - title: The Enterprise version of Headwind MDM includes a powerful module for transferring images taken by mobile devices to the server.
      url: https://h-mdm.com/wp-content/uploads/photo_plugin.jpg
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
