apiVersion: v2
name: headwind-mdm
description: Headwind MDM - an open source mobile device management software for Android
type: application
version: 1.0.0
appVersion: "0.1.0"
home: https://github.com/christianknell/helm-charts
icon: https://h-mdm.com/wp-content/uploads/2019/07/neew-logo.png
maintainers:
  - name: christianknell
    email: christian@knell.it
sources:
  - https://github.com/h-mdm/hmdm-docker
  - https://github.com/h-mdm
  - https://hub.docker.com/r/headwindmdm/hmdm
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.1.5
    condition: postgresql.enabled
