{{- if (not .Values.maildev.config.smtp.incoming.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maildev.smtp.incoming.secretName" . }}
data:
  smtp-incoming-password: {{ .Values.maildev.config.smtp.incoming.password | b64enc | quote }}
{{- end }}
