{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "bindy.labels" . | nindent 4 }}
  name: {{ include "bindy.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bindy.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bindy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
