{{- if and (.Values.persistence.enabled) (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  {{- if .Values.persistence.annotations }}
  annotations:
    {{- toYaml .Values.persistence.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "timetagger.labels" . | nindent 4 }}
  name: {{ include "timetagger.pvcName" . }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- with .Values.persistence.resources }}
  resources:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
