{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "timetagger.labels" . | nindent 4 }}
  name: {{ include "timetagger.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  credentials: {{ printf "%s:%s" .Values.auth.username .Values.auth.password | b64enc }}
{{- end }}
