apiVersion: v2
name: promlens
description: PromLens is a tool that makes learning and using PromQL easier and more productive
type: application
version: 1.2.0
appVersion: "v0.3.0"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/promlens/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/prometheus/promlens
  - https://hub.docker.com/r/prom/promlens
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - kind: changed
      description: hpa spec to align with v2
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/screenshots: |
    - title: Build, understand, and fix your queries much more effectively with the ultimate query builder for PromQL.
      url: https://promlens.com/static/promlens-hero-screenshot-7d453e779cf47c6fcec1de8823049257.png
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
