apiVersion: v2
name: syncserver
description: Helm chart for Firefox Syncserver
type: application
version: 1.0.0
appVersion: "latest"
home: https://github.com/christianknell/helm-charts
icon: https://think.unblog.ch/wp-content/uploads/2019/05/Firefox_Sync.png
maintainers:
  - name: Christian Knell
    email: christian@knell.it
sources:
  - https://hub.docker.com/r/mozilla/syncserver/
  - https://github.com/mozilla-services/syncserver
