apiVersion: v2
name: syncserver
description: Helm chart for Firefox Syncserver
type: application
version: 1.0.6
appVersion: "latest"
home: https://github.com/christianknell/helm-charts
icon: https://think.unblog.ch/wp-content/uploads/2019/05/Firefox_Sync.png
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://hub.docker.com/r/mozilla/syncserver/
  - https://github.com/mozilla-services/syncserver
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: support link
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
