apiVersion: v2
name: shlink-web
description: A  ReactJS-based progressive web application for Shlink.
type: application
version: 0.3.2
appVersion: "3.10.2"
home: https://github.com/christianknell/helm-charts
icon: https://shlink.io/images/shlink-logo-blue.svg
maintainers:
  - name: christianknell
    email: christian@knell.it
sources:
  - https://github.com/shlinkio/shlink-web-client
  - https://shlink.io
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: bumped image version to 3.10.2
  artifacthub.io/screenshots: |
    - title: Add a new link that should be shortened.
      url: https://alejandrocelaya.blog/assets/img/shlink-web-client-3/creation-form-after.png
    - title: You can have an overview of all your shortened links.
      url: https://shlink.io/images/shlink-web-client-placeholder.jpg
    - title: For each link there are multiple statistical data collected and visualized.
      url: https://alejandrocelaya.blog/assets/img/shlink-web-client-3/visits-after.png
    - title: A typical architecture in which Shlink would be integrated.
      url: https://shlink.io/images/architecture/shlink-architecture.png
