apiVersion: v2
name: shlink-web
description: A  ReactJS-based progressive web application for Shlink.
type: application
version: 1.10.0
appVersion: "4.6.2"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/shlink-web/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/shlinkio/shlink-web-client
  - https://shlink.io
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: support for deployment strategy
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/screenshots: |
    - title: Add a new link that should be shortened.
      url: https://alejandrocelaya.blog/assets/img/shlink-web-client-3/creation-form-after.png
    - title: You can have an overview of all your shortened links.
      url: https://shlink.io/images/shlink-web-client-placeholder.jpg
    - title: For each link there are multiple statistical data collected and visualized.
      url: https://alejandrocelaya.blog/assets/img/shlink-web-client-3/visits-after.png
    - title: A typical architecture in which Shlink would be integrated.
      url: https://shlink.io/images/architecture/shlink-architecture.png
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
