apiVersion: v2
name: timetagger
description: A Helm Chart for installing Timetagger, an open source time-tracker with an interactive user experience and powerful reporting.
type: application
version: 2.1.1
appVersion: "v26.1.1"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/timetagger/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/almarklein/timetagger
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: problem in hpa template
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
