apiVersion: v2
name: skooner
description: Simple Kubernetes real-time dashboard and management.
type: application
version: 0.0.6
appVersion: "stable"
home: https://github.com/christianknell/helm-charts
icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu8eQrFBosk7yHTiDEwjnVcMRyDD5uIaNXhlZ1m0yiC4H8RP1j0PlBPtgtv0bdH0JwlOE
maintainers:
  - name: christianknell
    email: christian@knell.it
sources:
  - https://github.com/skooner-k8s/skooner
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/screenshots: |
    - title: Overview of the workloads running inside of Kubernetes.
      url: https://skooner.io/images/k8dash-screen.png
    - title: Dashboard of the nodes and their resources.
      url: https://loft.sh/images/blog/posts/skooner-ui.png
