apiVersion: v2
name: skooner
description: Simple Kubernetes real-time dashboard and management.
type: application
version: 0.2.1
appVersion: "stable"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/skooner/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/skooner-k8s/skooner
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - kind: fixed
      description: helm schema
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/screenshots: |
    - title: Overview of the workloads running inside of Kubernetes.
      url: https://skooner.io/images/k8dash-screen.png
    - title: Dashboard of the nodes and their resources.
      url: https://loft.sh/images/blog/posts/skooner-ui.png
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
