{{- if and .Values.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "ntp-exporter.fullname" . }}
  {{- with .Values.podMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "ntp-exporter.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.selector }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.podMonitor.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: http
      {{- if (eq (include "ntp-exporter.exporter.auth.enabled" .) "0") }}
      params:
        {{- if .Values.config.exporter.auth.securityToken }}
        token:
          - {{ .Values.config.exporter.auth.securityToken | quote }}
        {{- else if .Values.config.mailcow.auth.apiKey }}
        token:
          - {{ .Values.config.mailcow.auth.apiKey | quote }}
        {{- end }}
      {{- end }}
      {{- with .Values.podMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      path: /metrics
      {{- with .Values.podMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "ntp-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
