{{- if and (not .Values.postgresql.enabled) (not .Values.externalPostgresql.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kutt.fullname" . }}
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
data:
  {{- include "kutt.postgresql.userPasswordKey" . | nindent 2 }}: {{ .Values.externalPostgresql.password | b64enc }}
{{- end }}
