apiVersion: v2
name: argocd-metrics-server
description: A Helm chart for installing the Argo CD Metrics Server, which connects to Prometheus and displays Metrics in the Argo CD UI
type: application
version: 0.0.1
appVersion: "v1.0.3"
home: https://github.com/christianhuth/helm-charts
icon: https://icon.icepanel.io/Technology/svg/Argo-CD.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/argoproj-labs/argocd-extension-metrics
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial Commit
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
