---
apiVersion: v2
name: kubedoom
description: A Helm chart for Kubedoom
version: 1.1.2
type: application
appVersion: "0.6.0"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/kubedoom/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/storax/kubedoom
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: problem in hpa template
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/screenshots: |
    - title: Kill pods inside your Kubernetes cluster by shooting them in Doom!
      url: https://github.com/storax/kubedoom/raw/master/assets/doom.jpg
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
