apiVersion: v2
name: github-exporter
description: A Helm Chart for the GitHub Prometheus Exporter
type: application
version: 1.0.1
appVersion: "1.3.1"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/github.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/githubexporter/github-exporter
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: support link
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
