apiVersion: v2
name: github-exporter
description: A Helm Chart for the GitHub Prometheus Exporter
type: application
version: 2.2.0
appVersion: "v2.1.0"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/github-exporter/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/githubexporter/github-exporter
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: support for Gateway API routes
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
