{{- if .Values.backend.asgi.autoscaling.enabled }}
{{- if semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta1
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "baserow.backend.asgi.fullname" . }}
  labels:
    {{- include "baserow.backend.asgi.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "baserow.backend.asgi.fullname" . }}
  minReplicas: {{ .Values.backend.asgi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.backend.asgi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.backend.asgi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend.asgi.autoscaling.targetCPUUtilizationPercentage }}
        {{- else }}
        targetAverageUtilization: {{ .Values.backend.asgi.autoscaling.targetCPUUtilizationPercentage }}
        {{- end }}
    {{- end }}
    {{- if .Values.backend.asgi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend.asgi.autoscaling.targetMemoryUtilizationPercentage }}
        {{- else }}
        targetAverageUtilization: {{ .Values.backend.asgi.autoscaling.targetMemoryUtilizationPercentage }}
        {{- end }}
    {{- end }}
{{- end }}
