name: Chart-Pipeline

on:
  push:
    paths: ["charts/**"]
  workflow_dispatch:

jobs:
  preparation:
    uses: ./.github/workflows/chart-preparation.yml

  linting:
    needs: [preparation]
    uses: ./.github/workflows/chart-linting.yml

  kubeconform:
    needs: [preparation, linting]
    uses: ./.github/workflows/chart-kubeconform.yml

  unit-testing:
    needs: [preparation, linting, kubeconform]
    uses: ./.github/workflows/chart-unittesting.yml

  testing:
    needs: [preparation, linting, kubeconform, unit-testing]
    uses: ./.github/workflows/chart-testing.yml

  releasing:
    if: github.ref == 'refs/heads/main'
    needs: [preparation, linting, kubeconform, unit-testing, testing]
    uses: ./.github/workflows/chart-releasing.yml
    secrets:
      GPG_PRIVATE_KEY_BASE64: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }}
      GPG_PRIVATE_KEY_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
      GPG_PRIVATE_KEY_UID: ${{ secrets.GPG_PRIVATE_KEY_UID }}
