name: Chart-Preparation

on:
  pull_request:
    branches: [main]
    paths: ["charts/**"]
  push:
    branches: [main]
    paths: ["charts/**"]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3

  documentation:
    needs:
      - pre-commit
    runs-on: ubuntu-latest
    container: ghcr.io/chgl/kube-powertools:latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if documentation is up-to-date
        run: generate-docs.sh && /usr/bin/git diff --exit-code HEAD

  changelog:
    needs:
      - pre-commit
    runs-on: ubuntu-latest
    container: ghcr.io/chgl/kube-powertools:latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update dependencies
        run: find charts/ ! -path charts/ -maxdepth 1 -type d -exec helm dependency update {} \;
      # used to test whether the changelog generation process works properly
      - name: Generate changelogs
        run: bash .github/generate-chart-changelogs.sh
